### ISSUE TITLE
ImageType string clipping

### ISSUE THREAD

**Issue by jmtyszka** [jmtyszka/dcm2niix#1]
I am seeing that the "ImageType" dicom field is getting clipped by dcm2niix 
This is an issue for the multiecho T1w, as the _NORM gets cut off from the 4th file that gets generated (combined and bias-corrected). It ends up being the same ImageType as the combined, non bias-corrected volume (the 3rd file), and thus there is no way to know which is which.

**Comment by jmtyszka** [comment]
Fixed: ImageType string length increased to 64 characters to accommodate options of latest Siemens sequences.

**Comment by jcrdubois** [comment]
This is still not behaving as needed.
Here is the ImageType in the header of one of my dicom files (combined MEMPRAGE bias-corrected):
ORIGINAL\PRIMARY\ECHO_COMBINED\ND\NORM

and here is what appears in the .json sidecar:
ORIGINAL_PRIMARY_ECHO_COMBINED

It may not be a string length issue, but rather the number of fields read from the "\" delimited header string? (limited to 3??)

**Comment by jmtyszka** [comment]
Redefined kDICOMstr to 64 in nii_dicom.h. Must have missed a dependence somewhere. Works for combined echo MEMP combined echo images now:
ORIGINAL_PRIMARY_ECHO_COMBINED_ND_NORM 38 38
ORIGINAL_PRIMARY_ECHO_COMBINED_ND 34 33

**Comment by jcrdubois** [comment]
I can confirm that issue is fixed, nice job!
- Julien
